baseURL = "https://yasoob.me/"
languageCode = "en-us"
title = "Yasoob Khalid"
author = "yasoob"
theme = "hugo-zen"
copyright = "CC-by-NA"
enableEmoji = true
googleanalytics = "UA-97849776-1"

[params]
	logo = "/images/profile.jpg"
	email = "hi@yasoob.me"
	twitter = "https://twitter.com/yasoobkhalid"
	github = "https://github.com/yasoob"
	linkedin = "https://www.linkedin.com/in/yasoob/"
	tagline = "Author, Blogger & artist who can't make up his mind."

	[params.staticman]
	endpoint = "https://staticman-blog.fly.dev/v2/entry"
	username = "yasoob"
	repository = "personal_blog"
	branch = "master"

[markup.goldmark.renderer]
  unsafe= true

[taxonomies]
  category = "categories"
  tag = "tags"

